### PR TITLE
Command autonomy tetrominomovementhandler

### PR DESCRIPTION
**Pull request by sebasv**

### CODE REVIEW

**Comment by karelvandoesburg** [comment]
I guess the conflict with the controller should be resolved before merging

**Comment by sebasv** [comment]
Consider the conflict resolved!

**Comment by karelvandoesburg** [comment]
doesn't this need to be tested?

**Comment by karelvandoesburg** [comment]
everything that is not the controller is tested. When these and the RoboMode will both be merged, it might be possible to test the controller and view. So I will merge it now

**Pull request merged**
