### PR TITLE
Pauze button added(easy method but it is working)

### PR DESCRIPTION
**Pull request by RobertLevenbach**
Do you guys think this is a good way?

### CODE REVIEW

**Comment by karelvandoesburg** [comment]
Look nice, should i write a test tomorrow?

**Comment by karelvandoesburg** [comment]
Or are you going to write tests yourself? Either way, i think I will merge. Let me know!

**Comment by RobertLevenbach** [comment]
I noticed Im ay have worked in the wrong master build... Dont know forsure but sometimes I go gameover and get an error... Will check this tomorow

**Comment by karelvandoesburg** [comment]
Won't calling the method gameOver() bring you to the HighScore board to give your name (if your score is already the highscore), when you still actually want to play?

**Comment by RobertLevenbach** [comment]
no i tested it and it works:) also the score doesn't reset so i think this method may work

**Comment by sebasv** [comment]
It looks allright, but could you rename pauze and unpauze to their English counterparts? I think Thomas will lose his shit if he would find out ;)

**Comment by RobertLevenbach** [comment]
haha true, maybe my musicroots are working against me.... I am also going to try and merge the pause and unpause buttons to one button

**Comment by RobertLevenbach** [comment]
I have chosen to do the same work in an other branch!

**Pull request closed without merging**
